### ISSUE TITLE
Delegate drag and drop to react-dnd?

### ISSUE THREAD

**Issue by okonet** [jrowny/react-absolute-grid#10]
I'm a fan of small components with an open API allowing composing them easily. [react-dnd](https://github.com/gaearon/react-dnd) is a perfect example of what I'm talking about. 

I'm wondering if drag'n'drop functionality could be removed from absolute-grid whatsoever. What do you think? I could do a PR to remove but not sure if you would accept it and be willing to release a new major version without it.

**Comment by jrowny** [comment]
I'm not familiar with the inner-workings of react-dnd, but I did try to use it originally (a long time ago) and found it wasn't able to handle the absolute layout required by the grid. 

If it's possible to have react-dnd do the heavy lifting and still allow us to have an absolute layout, then I'm open to it. Otherwise I'd like to keep it because the absolute layout is important for the sort and resize performance.
