### ISSUE TITLE
react-absolute-grid on mobile

### ISSUE THREAD

**Issue by lucasfeliciano** [jrowny/react-absolute-grid#4]
Hello,

I'm struggling for a while in a problem with animations + cordova. 
Any kind of implementation of animation that I try I do not get 20fps on the mobile enviroment.

Did you already tested on mobile?

Another question is:

Can I implement a list of itens instead of a grid?

**Comment by jrowny** [comment]
It is possible to implement a list by setting the item width to a fixed size which is greater than 1/2 the width of the target resolution. In this case the grid algo will not be able to fit two columns and only use one column. 

Unfortunately Cordova+Animations is just slow, especially on Android. The best solution I've found to that problem is using Intel's Crosswalk: https://crosswalk-project.org/

**Comment by lucasfeliciano** [comment]
Thank you for the reply :)
