### ISSUE TITLE
Export BaseDisplayObject

### ISSUE THREAD

**Issue by okonet** [jrowny/react-absolute-grid#7]
As far I can understand there is no way to create own `GridItem` without extending from `BaseDisplayObject`. Shouldn't it be exported in this case then?

**Comment by jrowny** [comment]
you mean from the main component?

I'm still pretty new to ES6 trying to figure out exactly what that'd look like. I chose inheritance of composition because I thought it would be easier to use, but now I'm thinking maybe I should just rewrite it to include a composition function in the main component. What do you think of that idea?

**Comment by okonet** [comment]
Yes, the API seemed strange to me. I'd prefer composition (the React way btw) to inheritance. So that you can write something like this:

```
<AbsoluteGrid {...props, gridItemComponent: MyGridItem} />
```

or similar. Should I try this out and file a PR? Either way, If you need any help, please let me know.

**Comment by jrowny** [comment]
Hey Andrey, I'm pretty busy so I'd love to see the composition approach if
you have time for a PR!

On Fri, Sep 25, 2015 at 11:36 AM, Andrey Okonetchnikov <
notifications@github.com> wrote:

> Yes, the API seemed strange to me. I'd prefer composition (the React way
> btw) to inheritance. So that you can write something like this:
>
> <AbsoluteGrid {...props, gridItemComponent: MyGridItem} />
>
> or similar. Should I try this out and file a PR? Either way, If you need
> any help, please let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jrowny/react-absolute-grid/issues/7#issuecomment-143254044>
> .
>



-- 
Jonathan
